import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

//Components
import Navbar from '@/components/Navbar'
import SearchBar from '@/components/SearchBar'
import Adsbar from '@/components/Adsbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Artwork Figures | Loja de produtos GEEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SearchBar />
      <Adsbar />
    </>
  )
}
