import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


//Components
import Navbar from '@/components/Navbar'
import SearchBar from '@/components/SearchBar'
import Adsbar from '@/components/Adsbar'
import Main from '@/components/Main'


export default function Home() {
  return (
    <>
      <Head>
        <title>Artwork Figures | Loja de produtos GEEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SearchBar />
      <Adsbar />
      <Main />
    </>
  )
}
