import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


//Components
import Navbar from '@/components/Navbar'
import SearchBar from '@/components/SearchBar'
import Adsbar from '@/components/Adsbar'
import Main from '@/components/Main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Artwork Figures | Loja de produtos GEEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
        <Link rel="preconnect" href="https://fonts.googleapis.com" />
        <Link rel="preconnect" href="https://fonts.gstatic.com" />
        <Link href="https://fonts.googleapis.com/css2?family=Slackey&display=swap" rel="stylesheet" />
      </Head>
      <Navbar />
      <SearchBar />
      <Adsbar />
      <Main />
    </>
  )
}
